# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "banner_animation"
pin "scroll_to"
pin "roulette_effect"
pin "roulette_footer_backTop"
pin "navbar_animation"
pin "parallax_effect"
pin "carousel_controller"
pin "header_height"
pin "burger"
